function Juu = REB_harris_simple(K,A,alpha,Q)
%REB_HARRIS_SIMPLE
%    JUU = REB_HARRIS_SIMPLE(K,A,ALPHA,Q)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Jan-2018 11:14:56

t2 = sin(alpha);
t3 = cos(alpha);
t4 = 1.0./A;
t5 = K.*t2.*t3;
t6 = t5-Q.*t2.*t3.*t4;
t7 = t3.^2;
t8 = t2.^2;
Juu = reshape([K.*t8+Q.*t4.*t7,t6,t6,K.*t7+Q.*t4.*t8],[size(K),2,2]);
