function [K,Juu,Juv,Jvu,Jvv] = REB_harris_inner(Ki,Ko,Ai,Ao,alpha_i,alpha_o,Qi,Qo,Oi,Oo,REB)
%REB_HARRIS_INNER
%    [K,JUU,JUV,JVU,JVV] = REB_HARRIS_INNER(KI,KO,AI,AO,ALPHA_I,ALPHA_O,QI,QO,OI,OO,REB.D,REBJBALL,REBMBALL,REB.DM,REBGAMMA,REBRCAGEI)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Jan-2018 11:03:48

t2 = cos(alpha_i);
t3 = sin(alpha_i);
t4 = 1.0./Ai;
t5 = cos(alpha_o);
t6 = sin(alpha_o);
t7 = t2.^2;
t8 = t3.^2;
t9 = t5.^2;
t10 = t6.^2;
t11 = Ki.*t2.*t3;
t40 = Qi.*t2.*t3.*t4;
t12 = t11-t40;
t13 = Qi.*Qo.*t7.*t10;
t14 = Qi.*Qo.*t8.*t9;
t15 = t7.^2;
t16 = Ao.*Ki.*Qi.*t15;
t17 = t9.^2;
t18 = Ai.*Ko.*Qo.*t17;
t19 = t8.^2;
t20 = Ao.*Ki.*Qi.*t19;
t21 = t10.^2;
t22 = Ai.*Ko.*Qo.*t21;
t23 = Ai.*Ki.*Qo.*t7.*t9;
t24 = Ao.*Ko.*Qi.*t7.*t9;
t25 = Ao.*Ki.*Qi.*t7.*t8.*2.0;
t26 = Ai.*Ko.*Qo.*t9.*t10.*2.0;
t27 = Ai.*Ki.*Qo.*t8.*t10;
t28 = Ao.*Ko.*Qi.*t8.*t10;
t29 = Ai.*Ao.*Ki.*Ko.*t7.*t10;
t30 = Ai.*Ao.*Ki.*Ko.*t8.*t9;
t31 = Ai.*Ki.*Qo.*t2.*t3.*t5.*t6.*2.0;
t32 = Ao.*Ko.*Qi.*t2.*t3.*t5.*t6.*2.0;
t38 = Qi.*Qo.*t2.*t3.*t5.*t6.*2.0;
t39 = Ai.*Ao.*Ki.*Ko.*t2.*t3.*t5.*t6.*2.0;
t33 = t13+t14+t16+t18+t20+t22+t23+t24+t25+t26+t27+t28+t29+t30+t31+t32-t38-t39;
t34 = 1.0./t33;
t35 = Ki.*t8;
t36 = Qi.*t4.*t7;
t37 = t35+t36;
t41 = Ao.*Qi.*t2.*t3;
t42 = Ai.*Qo.*t5.*t6;
t50 = Ai.*Ao.*Ki.*t2.*t3;
t51 = Ai.*Ao.*Ko.*t5.*t6;
t43 = t41+t42-t50-t51;
t44 = Ao.*Qi.*t8;
t45 = Ai.*Qo.*t10;
t46 = Ai.*Ao.*Ki.*t7;
t47 = Ai.*Ao.*Ko.*t9;
t48 = t44+t45+t46+t47;
t49 = t34.*t37.*t48;
t52 = t12.*t34.*t43;
t53 = t49+t52;
t54 = t34.*t37.*t43;
t55 = Ao.*Qi.*t7;
t56 = Ai.*Qo.*t9;
t57 = Ai.*Ao.*Ki.*t8;
t58 = Ai.*Ao.*Ko.*t10;
t59 = t55+t56+t57+t58;
t60 = t12.*t34.*t59;
t61 = t54+t60;
t62 = Ki.*t7;
t63 = Qi.*t4.*t8;
t64 = t62+t63;
t65 = t34.*t43.*t64;
t66 = t12.*t34.*t48;
t67 = t65+t66;
t68 = t34.*t59.*t64;
t69 = t52+t68;
K = reshape([t35+t36-t12.*t61-t37.*t53,t11-t40-t12.*t69-t37.*t67,t11-t40-t12.*t53-t61.*t64,t62+t63-t12.*t67-t64.*t69],[size(Ki),2,2]);
if nargout > 1
    t70 = -t11+t40;
    t71 = reshape([t37,t12,t12,t64],[size(Ki),2,2]);
    Juu = t71;
end
if nargout > 2
    Juv = reshape([-t35-t36,t70,t70,-t62-t63],[size(Ki),2,2]);
end
if nargout > 3
    Jvu = t71;
end
if nargout > 4
    t72 = 1.0./Ao;
    t73 = Qo.*t5.*t6.*t72;
    t74 = -t11+t40+t73-Ko.*t5.*t6;
    Jvv = reshape([-t35-t36-Ko.*t10-Qo.*t9.*t72,t74,t74,-t62-t63-Ko.*t9-Qo.*t10.*t72],[size(Ki),2,2]);
end
